language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: gae
  keyfile: hn-sentiment-3b3b291ae079.json
  project: hn-sentiment
  # version: prod # Turn this back on if you don't want a new version created with each build.
  default: true
before_install:
- openssl aes-256-cbc -K $encrypted_ec3aeee44a4a_key -iv $encrypted_ec3aeee44a4a_iv
  -in hn-sentiment-3b3b291ae079.json.enc -out hn-sentiment-3b3b291ae079.json -d