apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentiment-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sentiment-server
    spec:
      containers:
      - name: sentiment-container
        image: gcr.io/hn-sentiment/sentiment
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sentiment-service
  name: sentiment-service
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: sentiment-server
  type: LoadBalancer